### ISSUE TITLE
Security review

### ISSUE THREAD

**Issue by swentel** [swentel/indieweb#196]
We need this. Let's try to find someone who can break this :)

Also: if you find something that's really really scary, please let know me first privately.
While this module isn't used much (probably only me right now), it's safer to handle this with care.

Focus points:

- micropub endpoint
- indieauth endpoints
- token JWT generation and validation
- microsub endpoints
- webmention endpoints
- indieauth endpoints (especially token security on built-in endpoint)
- permissions
- move secret of webmention point out of config ? Or encrypt it ?

**Comment by swentel** [comment]
Hey @tatarbj ,

I'm totally fine with both approaches, although I have a preference to file separate issues. We  can use this one as a 'meta' track them. I added a 'security' label to the project, so we can use that to group them too.

**Comment by tatarbj** [comment]
Hey @swentel,

For the first round, I'd address these issues, but I need more time to check all forms and their actions, also to test the functionality that looks potentially insecure (like remote executions on entities as I've seen module can allow it). I'm also not fully sure the proper way is implemented for the confirm forms even the one that I've spotted extends the base class, further tests are needed.

So here we go:

- Usage of check_markup(). As it’s indicated on its documentation, it shouldn’t be used when rendering happens, rather than a renderable array with the #type ‘processed_text’ (see https://api.drupal.org/api/drupal/core%21modules%21filter%21filter.module/function/check_markup/8.6.x). Currently 3 places call check_markup() and it seems all of them fail to follow this practice (in a block's build(), in a controller’s private method and a template_preprocess)

- Permissions. I would suggest marking the administer permissions restricted. It’s a security best practice that highlights these permissions on the admin/people/permissions page with an extra text to let site builders know the permission should be only given to trusted user roles. It’s not necessary a blocker for stable release, but if a vulnerability is discovered in the module and it’s not protected by a restricted permission, then the issue will result in a security advisory and mustn’t be public hardened.

Let me know how would you address these two, I even can create here some PRs, fixing these two, but I'm more on the research side now :)

Bests,
Balazs.

**Comment by swentel** [comment]
regarding permissions: makes sense. PR is fine :)

Regarding check_markup: I noticed that in AuthorBlock it also still used a hardcoded markup field haha. It should get it from $this->configuration['note']. But yes, text_processed is probably better, and maybe also a select box on the author block to select a text format. That makes it way more flexible.

For the other two check_markup calls, the background is this: webmentions can contain a text and html property when they are send to the site. I decided to use the text version because that's the safest one to begin with, plus, usually, those are just comments on an article on the site. The text version has newlines, so I used check_markup to make sure at least we have some paragraphs. So yeah, this should probably use text_processed too, but maybe nl2br is even the easiest solution, since they shouldn't/won't contain tags anyway.

**Comment by swentel** [comment]
I've fixed the authorblock $markup variable, as in, use the right source to begin with, no other conversions for now.

**Comment by swentel** [comment]
Another heads up, the webmention and indieauth endpoints are in.
All functionality has been split up also.
One important last thing to tackle is the generation of the access tokens.
Getting close.

**Comment by swentel** [comment]
RC 1 is out, my personal goal for 1.0 is end of february, will see if we get there :)

**Comment by swentel** [comment]
This can be closed since 1.0 is out.
Security reviews are still welcomed of course :)
