### ISSUE TITLE
Twitter login no longer works?

### ISSUE THREAD

**Issue by jepster** [swentel/indieweb#333]
I have tried to use the Indieweb Drupal module and the Indigenious Android app. As far I can understand, I need a social media profile to connect to my website, My website is https://mobilefish.de and I placed a social media link in the header to link my Twitter profile to my website Mobilefish.de:

`<a href="https://twitter.com/netzor" rel="me">Twitter</a>`

Also I have set my sites domain in my Twitter profile. If I want to sign in into my site via the Indigenious Android app, I see the following message from IndieAuth.com:
![screenshot_20181125-135744](https://user-images.githubusercontent.com/628434/48979378-62faff80-f0ba-11e8-967a-30f38ea73774.jpg)

Is Twitter not longer a "citizen" of the Indieweb? Is there any other way around this to support Twitter?

**Comment by swentel** [comment]
Indeed not. IndieAuth.com has dropped support for twitter recently (due to twitter HTML changes)
GitHub should still work though.

Another way is to use internal indieauth endpoint of course. I just committed some code for harder token generation to the dev branch (also on d.o), then you don't have to setup RelMeAuth at all.
(in case you'd checkout the dev branch, make sure to run composer update as there's an additional dependency on a 3rd party client).

**Comment by jepster** [comment]
Thanks for your quick reply. I will try the dev branch.
