### ISSUE TITLE
Add a p-author (with h-card) entity reference and link formatters

### ISSUE THREAD

**Issue by mlncn** [swentel/indieweb#354]
Our use case is a content type (Blog posts) which on [Drutopia](https://gitlab.com/drutopia/drutopia) has entity reference to a Person content type (to allow multiple authors and to enable authorship to be attributed to profiles of people who do not necessarily have an account on the site).

Another common alternative way of attributing authorship to a piece of content would be a link to a person's off-site profile.

Providing link and entityreference formatters would allow Indieweb module to support both these use cases.

**Comment by mlncn** [comment]
Given the strong recommendation in https://indieweb.org/authorship and from other indieweb implementers to use the embedded h-card option when including authors, decided not to add the complexity of having p-author without h-card as an option.

Also using p-author and not u-author because p-author is what [h-entry](http://microformats.org/wiki/h-entry) defines.

**Comment by swentel** [comment]
I guess this relates to #165 - although that one is more of a meta-issue to start splitting of sub issues as it would take a while to implement it everywhere within the module.

https://indieweb.org/authorship#How_to_publish describes u-author as valid as well, but only if there's an author h-card somewhere (being either homepage, or on the same page). Aaron uses ```<a class="u-author" href="/"></a>``` everywhere and I guess I always followed his example because then I know my mf2 parsing whould work)

So, somehow, it feels to me that p-author is rather for partially/fully embedded h-cards when we don't necessarily know the link, but maybe my interpretation is wrong. However, I'm fine with this too, as long as the mf2 parsers find the information :)
  
There's another place where there's a hardcoded link, which is in indieweb_microformat_preprocess_node(). It feels like we need an option/setting on the microformats settings page to

- either point to the home page (which it currently does)
- or use the user profile page (I guess user/x is fine although that would not fix your use case where the profile is a content type)

Btw, I saw you talking about in IRC yesterday, so I wasn't suprised this was coming :)

**Comment by mlncn** [comment]
:-)

**Comment by mlncn** [comment]
Happy to do further work as directed; and apologies for making the merge request *slightly* before i had it working even for me.  As of now i think it basically works well, and i think should not break existing sites given that the default for the entityreference is kept as p-category.  But the ID for the entityreference formatter in code (entity_reference_label_p_category_class) is no longer accurate; i can try changing that and adding an update hook for existing sites...  and now that i think of it, the default is only for the form, so this would need an update hook anyway to set p-category for all existing entity reference labels set to use microformats.

Will code that if this approach is OK!  I haven't quite followed what the impact of the comments above should be for this merge request, but i'll take another read in the morning.

Thank you so much for all your incredible work on this module!

**Comment by swentel** [comment]
> But the ID for the entityreference formatter in code (entity_reference_label_p_category_class) is no longer accurate

Hmm right. I think changing the id is fine, but maybe to something even more generic, say 'entity_reference_label_microformat' because I wouldn't be surprised if more classes would be added there in the future.

As for an upgrade path. I'm totally fine just adding this to the release notes, since it's easy to change in the UI. There might be a fatal during rendering as the plugin id will not exist anymore, but IIRC, Field UI doesn't crash if the class of the default setting doesn't exist anymore.

**Comment by mlncn** [comment]
(OK as of 9268686 pushed two minutes ago it works as i intended..  and victorious on this fine solstice night, i off to bed)

And awesome!  OK i'll change the ID and then go to bed; definitely still willing to do an update hook since i got here after the super exciting release candidate!

**Comment by mlncn** [comment]
There was no fatal error after changing the ID, but it does silently stop working until editing / resaving the display configuration page.

**Comment by swentel** [comment]
> There was no fatal error after changing the ID, but it does silently stop working until editing / resaving the display configuration page.

I can totally live with that. Given the number of users using the module, I feel more comfortable with a release note. Also the impact of the original class is very minimal.

Also, re: the hardcodeness in indieweb_microformat_preprocess_node(), I'll split that off once I merge this issue in, so don't worry about this one yet.

Thanks for the code (and testing!). I'm off now too (not to bed, just woke up hehe), will merge tomorrow !
