### ISSUE TITLE
Comments not being created

### ISSUE THREAD

**Issue by sonniesedge** [swentel/indieweb#389]
Thank you so much for this module! Loving it. ❤️

But I have encountered a bug. While my site always receives the webmentions without a problem, the transformation from reply to comments not always guaranteed. 

More often than not I see the following in my logs. 

```
Failed to create a comment: The internal path  component 'https://www.sonniesedge.net/notes/2142' is invalid. Its path  component must have a leading slash, e.g. internal:/foo.
```

The domain is not being stripped before attempt to create the comment occurs.

**Comment by swentel** [comment]
Thanks :)

So that means that the value of the target of that webmention is still the full url after it has been processed right - it hasn't become /notes/2142? It's weird that it fails now and then, which is well, confusing. 

I have one idea though: are you processing the webmentions with drush in a cron? If so, are you passing on your domain name to the command, e.g., my drush command in the cron is set like this:

```
drush indieweb-process-webmentions -l https://realize.be
```

This way, drush tells Drupal it's running with that domain and not with 'default'. If that works, I should definitely update the README/docs to include that as it's well, quite critical to work (besides that, I've been thinking to change that piece of code to not strip the domain, but might be too late, and also tricky).

If this is the case, on 'admin/content/webmention', every webmention now has a reprocess link (8.x-1.0-rc4 release), so you can always hit that, let drush do it's job and the comment should be created then.

If none of this applies, then I have to think some more, but that will be for tomorrow :)

**Comment by sonniesedge** [comment]
I was processing the webmentions as part of the system cron task.

I've disabled that and I'm now running them directly via a drush command in the crontab. 

```
drush indieweb-process-webmentions -l https://www.sonniesedge.net
```

This seems to work, reprocesses included!  🎉

Thanks for the assistance. 😄

**Comment by swentel** [comment]
Ok, cool! Update the README to add that to the section of drush commands.
