### ISSUE TITLE
Decoupled Drupal, static site generators, and Indieweb

### ISSUE THREAD

**Issue by sonniesedge** [swentel/indieweb#408]
A bit of a long issue here, sorry! But I hope it's helpful to future development and other contributors.

The [Decoupled Drupal](https://dri.es/how-to-decouple-drupal-in-2019) approach is becoming more popular, allowing the use of Drupal as a headless CMS, exposing the Drupal data structure via a [JSON API](https://www.drupal.org/project/jsonapi) and generating the frontend via [another](https://www.gatsbyjs.org) [technology](https://www.11ty.io) altogether. 

Given an approach of generating a site via a static site generator and a service such as [Netlify](https://www.netlify.com), how can the Indieweb module integrate with that?

At the moment this is not entirely possible. 

Current scenario:

- A node is created in a headless Drupal installation running Indieweb. 
- In the node create interface the node author chooses to send a webmention to Brid.gy, (or any other webmention-friendly destination).
- The node is created, with a public URL
- A webmention is queued and eventually sent.
- The destination site receives the webmention and (potentially immediately) scans our public URL for microformats and handles it as it desires. 

If the site were decoupled into a headless CMS and a static site generator the scenario would not work.

- The Drupal installation would likely be on a different subdomain to the actual public site (e.g. cms.mydomain.org vs www.mydomain.org). The sent webmention would therefore have a different domain to the actual published site.
- The public URL would not be immediately created. A static site generator adds several minutes of lag to this, as a web hook must be sent from Drupal to the static site building service, which must bootstrap a new site, read data from the public API, download all data (including images), build the new site, and publish it. 
- In this time the queued webmention would likely have been sent. Even if it were somehow to magically have the correct domain then the public path might still not be available, as it would be in the process of being built. The receiving site would therefore find no URL and no microformat data to read.

This is just one scenario - others would likely be effected as well (e.g. receiving webmentions, indieauth, etc). 

## Solution

At least for webmentions, could this be solved by the following?:

- Be able to specify a public domain in Indieweb
  - all webmentions would be sent with this, rather than the Decoupled Drupal domain.
  - all received webmentions would use be compared against this public domain.
- When sending webmentions the Indieweb module would check that the public URL exists before trying to send it to another site. If it does not return a 200 then it stays in the queue until the next sending run.

There are plenty of other areas that this could effect, but I do not have as much knowledge of them.

Would the above solution be feasible?

**Comment by swentel** [comment]
> Would the above solution be feasible?

Absolutely. Just make sure you don't mix up domains in .drushrc ;)

Joke aside, I will probably struggle longer on writing a good test for this than the actual implementation, but with some luck, I can get this in over the weekend!

I'm slowly refactoring some callbacks too on my site - Vue.js where some callbacks use jsonapi already, but not all, specifically webmentions is still a custom response. I know they are exposed by JSONAPI, but If you have feedback or suggestions there, feel free to open an issue on that because it's on my radar already.

**Comment by swentel** [comment]
This is in :)

Note: it's only in the dev release right now - not sure exactly when a new release is out as I'm planning some more things. Download from https://www.drupal.org/project/indieweb/releases/8.x-1.x-dev 

I have tests that work for sending (doesn't remove from queue until 200) and receiving (this was actually not a problem at all, but it doesn't hurt to have a dedicated test with two domains).

I might miss things since I don't run such a setup at the moment, so if you run into problems, open issues!

**Comment by sonniesedge** [comment]
Oh my gosh, this is amazing to come back to after the Easter weekend! 

Thank you for implementing the ideas I suggested! 

I will of course try this as soon as possible and raise issues if necessary.

🎉
