### ISSUE TITLE
Deleting outgoing webmentions in queue

### ISSUE THREAD

**Issue by sonniesedge** [swentel/indieweb#419]
Is it possible to clear the queued outgoing webmentions? I've got a bunch that seem to have been sat there for weeks, and I've got the feeling I'm bombing brid.gy with them every time the queue is processed. Where about are they stored?

**Comment by sonniesedge** [comment]
Ah, found the table. Didn't realise there was a queue system in Core.

**Comment by swentel** [comment]
It's in the queue table indeed. The good thing about bridgy is that it doesn't allow duplicates. 

Do you remember whether 'expire' was 0 or some really big number for those that were stuck ?
If so, then I should probably expose that in the table since they will be stuck forever then probably, so a delete/reset option might not be a bad idea.

Note: I've seen that there's a lot of activity on your blog, a lot of incoming webmentions, so it's cool to see it's able to handle it - as far as I know of course :)

**Comment by sonniesedge** [comment]
> The good thing about bridgy is that it doesn't allow duplicates.

Yeah, was just more worried about annoying them off by sending them duplicate webmentions every 2 minutes! 

> Do you remember whether 'expire' was 0 or some really big number for those that were stuck?

Definitely 0.  

> Note: I've seen that there's a lot of activity on your blog, a lot of incoming webmentions, so it's cool to see it's able to handle it - as far as I know of course :)

Yes, it seems to be working very well! The only problems I ever face come failed sends from the twitter side of brid.gy, which is due to the twitter API being awful. 

I've got a few requests and comments on how things work in general for this module, based on my usage. Would you like me to raise issues here, or contact directly?

**Comment by swentel** [comment]
> I've got a few requests and comments on how things work in general for this module, based on my usage. Would you like me to raise issues here, or contact directly?

Hmm, mail is fine (swentel at realize dot be), I can always extract issues then from it :)
