### ISSUE TITLE
User picture is replaced with wrong picture in comment replies

### ISSUE THREAD

**Issue by aleksip** [swentel/indieweb#425]
When 'Replace comment user picture' is enabled in the webmention formatter and replying to a comment, the user picture in the reply is replaced with the user picture from the comment being replied to. This happens whether the author replying has a local profile picture or not.

**Comment by swentel** [comment]
Thanks for the report!

One quick question: do you have the indieweb_microformat module enabled? I'm asking because the actual replacement happens in that module. Which, when I look at the code now, is kind of weird. I probably had a good reason to put it there, but I can't remember why anymore. In case it's not enabled, I should hide that setting because it doesn't make sense. And otherwise it's a bug of course.

I'll double check anyway to make sure of course, but it would be good to know your setup as well.

**Comment by aleksip** [comment]
Yes I have all IndieWeb modules enabled! 😊

**Comment by swentel** [comment]
Ok, I'll have to triple check then, because I remember this working when writing it :)

**Comment by swentel** [comment]
So I double checked, it's working fine on my setup, see screenshot. Trying to think what exactly might go wrong on your setup now. You are seeing the user picture from the paren comment basically right?

![user-picture](https://user-images.githubusercontent.com/168466/66029168-aef6ac00-e4f6-11e9-9a0a-8b807b3cefee.png)

**Comment by aleksip** [comment]
Well this is odd, but this is not happening any more on my site. What has also changed is that a 'Webmention info' or similar section disappeared from the comment reply form. I did wonder about the info as it was for the comment I was replying to and did not seem to have any function in the reply form. There could have been something wrong with my display settings, I don't know. 🤷🏻‍♂️

Anyway, closing this, thanks once again for all the help!
