### ISSUE TITLE
Will repost means retweet?

### ISSUE THREAD

**Issue by sparxsys** [swentel/indieweb#521]
I am trying the indigenous app on my Drupal site. Liking twitter post is working great but when I tried to repost it did not retweet.

The micropub for repost is enabled and I ran the cron to test it. Bridgy is also configured.

Thanks for the great set of modules. They are great.
Ravi

**Comment by swentel** [comment]
Repost will post the url in the repost-of property. You'll have to toggle a syndication target as well, in case of twitter it should be the brid.gy syndication target. After that, brid.gy should handle it. If it isn't posted there, there might be something wrong with the markup configuration: there's a formatter for repost in the manage display settings for the field.

**Comment by sparxsys** [comment]
Hi @swentel 

Thanks for the reply, I think the class in the manage display was set to "Like" and that explains why even my repost was only liking the tweet instead of reposting. Actually I have been using single content type called "Note" for note, like and checkin. So I guess using a separate content type for each type would make sense.

**Comment by swentel** [comment]
Indeed. A separate content type works better here because then you can different displays (and settings for those formatters).

The field (storage) can be the same over all content types though, that doesn't matter. That's how I've done my setup as well. That allows for less 'selects' in that 'link field' in case you want to send a webmention to site directly instead of using syndication targets like bridgy or others.
